#github actions to deploy Lecture rooms management system.

name: Deploy LRMS
on: 
    workflow_dispatch:
jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup .Net Core
                uses: actions/Setup-dotnet@v2
                with: 
                    dotnet-version: 7.0.x
            -   name: Install dependencies
                run: dotnet restore LetureRoomMgt.csproj

            -   name: build
                run: dotnet build LectureRoomMgt.csproj --configuration release --no-restore



