stages:
    - build
  
  build:
    stage: build
    image: docker:stable
    services:
      - docker:dind
    script:
      - docker build -t lrmsDI .
      - docker push lrmsDI
    only:
      - main
  