name: sast sonar
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  sastSonar:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sonar scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args: >
            -Dsonar.organization=chandrasiris
            -Dsonar.projectKey=LecRoomMgtSys
            -Dsonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml
      - name: Upload SonarCloud Analysis Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarcloud-report
          path: LectureRoomMgt/SecurityAnalysis/Sonar
