name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    - name: Restore dependencies
      run: dotnet restore --source ./nugetpackages --source https://api.nuget.org/v3/index.json
      working-directory: ${{ github.workspace }}
      
    - name: Run Roslyn Analyzers
      run: dotnet build /p:RunAnalyzersDuringBuild=true
      
    - name: Run StyleCop.Analyzers
      run: dotnet build /p:StyleCopEnabled=true
