name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    - name: Restore dependencies
      run: dotnet restore --source ./nugetpackages --source https://api.nuget.org/v3/index.json
      working-directory: ${{ github.workspace }}
      
    - name: Run unit tests
      run: dotnet test --no-restore --verbosity normal
